x-build-args: &build_args
  IMAGE_TAG: ${IMAGE_TAG}
  SLURM_TAG: ${SLURM_TAG}
  EAR_TAG: ${EAR_TAG}

services:
  mysql:
    image: mariadb:10.3.39
    container_name: mysql
    cpuset: "1"
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
    volumes:
      - var_lib_mysql:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d:ro
    networks: [slurm-network]
    expose: ["3306"]

  base:
    build:
      context: .
      dockerfile: Dockerfile.base
      args: *build_args
    image: slurm-ear-base:${IMAGE_TAG}
    deploy:
      replicas: 0

  slurmdbd:
    build:
      context: .
      dockerfile: Dockerfile.slurmdbd
      args: *build_args
    image: slurm-ear-slurmdbd:${IMAGE_TAG}
    container_name: slurmdbd
    cpuset: "2"
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose: ["6819"]
    networks: [slurm-network]

  slurmctld:
    build:
      context: .
      dockerfile: Dockerfile.controller
      args: *build_args
    image: slurm-ear-controller:${IMAGE_TAG}
    container_name: slurmctld
    cpuset: "2"
    hostname: slurmctld
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - etc_ear:/etc/ear
    expose: ["6817"]
    networks: [slurm-network]

  c1:
    build:
      context: .
      dockerfile: Dockerfile.node
      args: *build_args
    image: slurm-ear-node:${IMAGE_TAG}
    hostname: c1
    container_name: c1
    privileged: true
    cpuset: "4,5"
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - etc_ear:/etc/ear
      - var_log_ear_c1:/var/ear
    expose: ["6818", "5000"]
    networks: [slurm-network]

  c2:
    build:
      context: .
      dockerfile: Dockerfile.node
      args: *build_args
    image: slurm-ear-node:${IMAGE_TAG}
    hostname: c2
    container_name: c2
    cpuset: "6,7"
    privileged: true
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - etc_ear:/etc/ear
      - var_log_ear_c2:/var/ear
    expose: ["6818", "5000"]
    networks: [slurm-network]

  eardbd:
    build:
      context: .
      dockerfile: Dockerfile.eardbd
      args: *build_args
    image: slurm-ear-eardbd:${IMAGE_TAG}
    container_name: eardbd
    cpuset: "3"
    hostname: eardbd
    volumes:
      - etc_ear:/etc/ear
      - var_log_ear_dbd:/var/ear
    expose: ["4711", "4712", "4713"]
    networks: [slurm-network]

  eargm:
    build:
      context: .
      dockerfile: Dockerfile.eargm
      args: *build_args
    image: slurm-ear-eargm:${IMAGE_TAG}
    container_name: eargm
    cpuset: "3"
    hostname: eargm
    volumes:
      - etc_ear:/etc/ear
      - var_log_ear_gm:/var/ear
    expose: ["50000"]
    networks: [slurm-network]

volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:
  etc_ear:
  var_log_ear_c1:
  var_log_ear_c2:
  var_log_ear_gm:
  var_log_ear_dbd:


networks:
  slurm-network:
    driver: bridge